# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpg_api.swagger_models.base_model_ import Model
from rpg_api.swagger_models.lootbox_rarety import LootboxRarety  # noqa: F401,E501
from rpg_api import util


class Loot(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, slot: int=None, image_url: str=None, type: LootboxRarety=None):  # noqa: E501
        """Loot - a model defined in Swagger

        :param name: The name of this Loot.  # noqa: E501
        :type name: str
        :param slot: The slot of this Loot.  # noqa: E501
        :type slot: int
        :param image_url: The image_url of this Loot.  # noqa: E501
        :type image_url: str
        :param type: The type of this Loot.  # noqa: E501
        :type type: LootboxRarety
        """
        self.swagger_types = {
            'name': str,
            'slot': int,
            'image_url': str,
            'type': LootboxRarety
        }

        self.attribute_map = {
            'name': 'name',
            'slot': 'slot',
            'image_url': 'image_url',
            'type': 'type'
        }
        self._name = name
        self._slot = slot
        self._image_url = image_url
        self._type = type

    @classmethod
    def from_dict(cls, dikt) -> 'Loot':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The loot of this Loot.  # noqa: E501
        :rtype: Loot
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this Loot.


        :return: The name of this Loot.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Loot.


        :param name: The name of this Loot.
        :type name: str
        """

        self._name = name

    @property
    def slot(self) -> int:
        """Gets the slot of this Loot.


        :return: The slot of this Loot.
        :rtype: int
        """
        return self._slot

    @slot.setter
    def slot(self, slot: int):
        """Sets the slot of this Loot.


        :param slot: The slot of this Loot.
        :type slot: int
        """

        self._slot = slot

    @property
    def image_url(self) -> str:
        """Gets the image_url of this Loot.


        :return: The image_url of this Loot.
        :rtype: str
        """
        return self._image_url

    @image_url.setter
    def image_url(self, image_url: str):
        """Sets the image_url of this Loot.


        :param image_url: The image_url of this Loot.
        :type image_url: str
        """

        self._image_url = image_url

    @property
    def type(self) -> LootboxRarety:
        """Gets the type of this Loot.


        :return: The type of this Loot.
        :rtype: LootboxRarety
        """
        return self._type

    @type.setter
    def type(self, type: LootboxRarety):
        """Sets the type of this Loot.


        :param type: The type of this Loot.
        :type type: LootboxRarety
        """

        self._type = type
