# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpg_api.swagger_models.base_model_ import Model
from rpg_api import util


class LootboxRarety(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, name: str=None, value: int=None):  # noqa: E501
        """LootboxRarety - a model defined in Swagger

        :param name: The name of this LootboxRarety.  # noqa: E501
        :type name: str
        :param value: The value of this LootboxRarety.  # noqa: E501
        :type value: int
        """
        self.swagger_types = {
            'name': str,
            'value': int
        }

        self.attribute_map = {
            'name': 'name',
            'value': 'value'
        }
        self._name = name
        self._value = value

    @classmethod
    def from_dict(cls, dikt) -> 'LootboxRarety':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The lootbox_rarety of this LootboxRarety.  # noqa: E501
        :rtype: LootboxRarety
        """
        return util.deserialize_model(dikt, cls)

    @property
    def name(self) -> str:
        """Gets the name of this LootboxRarety.


        :return: The name of this LootboxRarety.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this LootboxRarety.


        :param name: The name of this LootboxRarety.
        :type name: str
        """

        self._name = name

    @property
    def value(self) -> int:
        """Gets the value of this LootboxRarety.


        :return: The value of this LootboxRarety.
        :rtype: int
        """
        return self._value

    @value.setter
    def value(self, value: int):
        """Sets the value of this LootboxRarety.


        :param value: The value of this LootboxRarety.
        :type value: int
        """

        self._value = value
