# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from rpg_api.swagger_models.base_model_ import Model
from rpg_api import util


class OneOfinventoryItems(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self):  # noqa: E501
        """OneOfinventoryItems - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'OneOfinventoryItems':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The OneOfinventoryItems of this OneOfinventoryItems.  # noqa: E501
        :rtype: OneOfinventoryItems
        """
        return util.deserialize_model(dikt, cls)
