openapi: 3.0.0
servers:
- url: https://localhost:8080
  description: Local server 
info:
  description: Simple API to play RPG ⚔
  version: 1.0.0
  title: RPG API
  contact:
    email: jloup.m@gmail.com
  license:
    name: MIT License
    url: 'http://opensource.org/licenses/MIT'
tags:
  - name: Information
    description: All possible informations
  - name: Action
    description: All possible actions 
paths:
  /get_balance/{user}:
    get:
      tags:
        - Information
      summary: Get balance information for a specific user
      operationId: get_balance
      description: |
        Return the balance of a specific user 
      parameters:
        - in: path
          name: user
          description: the username of the user
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Balance information
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/balance'
        '400':
          description: bad input parameter
      x-openapi-router-controller: rpg_api.controllers.balance_controller
      
components:
  schemas:
    balance:
      type: object
      properties:
        balance:
          type: number
      example:
        balance: 300